### PR TITLE
Architecture

### PR DESCRIPTION
**Pull request by illright**
architecture
This is how it's looking so far. I'm planning to add the methods where it's applicable and documentation later.

### CODE REVIEW

**Comment by illright** [comment]
architecture
Ready for review

**Comment by aabounegm** [comment]
1. Why do we have a `GazeDetector` that transforms a video to a gaze code (an "intermediate representation"), but not something similar for audio? Perhaps there should be a module that processes the audio and produces values summarizing it, such as type of audio (speech, background noise, music, ...), loudness, proximity (a stereo mic can help with locating the source), and so on; and then these values can be used by the `EngagementEstimator`.
2. What do the horizontal dotted lines represent?
3. And why are the mouse/keyboard info being written to a file as well as the DB?
4. What is the use of `SinkBase`? Doesn't seem to have any fields or be `implement`ed anywhere.
5. Shouldn't the interface of `ProcessorBase` define something that gives it the input source?
6. About the `SQLiteStore`, I think there shouldn't be separate functions for storing "engagement state" and mouse/keyboard. These data should be together. Like, for each new keyboard input, we store with it the current engagement state
7. Where is this diagram stored? (What is there to be merged in this PR?)

_P.S.: There is a typo in `MouseCompressor`: redu~d~**c**e_

**Comment by illright** [comment]
1. Added `SpeechDetector`.
2. Just visual separation of sources, processors and sinks.
3. They are written to the file in `vpt check` but to the DB in `vpt record`.
4. `SinkBase` is implemented by all sinks, it just doesn't have any methods so I omitted it. It's there just for the sake of hierarchy.
5. I thought about it, but no, I don't think we can reasonably have it rather that just subscribing to individual streams.
6. It's not really for each keyboard input. We store keyboard and mouse data all the time, and we store engagement levels only when they change. Analysis comes later on.
7. Oh, I swear I checked it in. Weird.

**Comment by illright** [comment]
architecture

**Review by IamMaxim — APPROVED** [review]

**Review by aabounegm — APPROVED** [review]

**Review by alkaitagi — APPROVED** [review]

**Comment by kuredoro** [comment]
`FileStore` has `store_engagement` method, but there's no data flow from `EngamentEstimator` to the `FileStore`. Similarly, there is a data flow from audio source to the `FileStore` but no method for processing audio streams.

**Comment by kuredoro** [comment]
Theere's a typo in `MouseCompressor`: redu~~d~~ce redundancy. Also, it's kinda redundant :) Maybe change to "less redundant"?

**Comment by illright** [comment]
architecture

**Review by kuredoro — APPROVED** [review]

**Pull request merged**
